### ISSUE TITLE
Clarify what the "earthsim examples" command does

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#173]
On the "Getting Started" page (http://earthsim.pyviz.org/getting_started ), under the `Usage` section,    
`cd earthsim-examples`  
should be changed to    
`cd examples`

**Comment by ceball** [comment]
Actually, `earthsim-examples` is deliberate. I'll try to explain the scheme - please tell us if you think it makes sense or not!

First, pretend for moment that earthsim's already a typical python package that can easily be installed via normal mechanisms (e.g. conda install earthsim or pip install earthsim). E.g. imagine it's like datashader. How can a user get their own copy of the examples to play around with? We could ask them to download the examples from somewhere, but instead we ship the examples with the package, and provide a command for the user to get their own (editable) copies of the examples: `datashader examples`. This command finds the examples in the datashader package, and copies them to wherever the user wants (by default, `datashader-examples` in the current directory). It also fetches any data necessary to run the examples. We think this approach would also make sense for earthsim (when it's easily installable in the future).

However, we think the same command might also be useful for developers, even though it's probably not the way you (or indeed most pyviz developers) work at the moment. I think most developers run and edit the example notebooks directly in the github repository's `examples/` directory. When the time comes to submit your work back to git, you do something like: stop the notebook, clear it (all outputs and user-/system-specific metadata), and then commit it. Or if you need to get new changes from git, you do something similar (clearing all outputs and metadata so that you don't get merge conflicts). This process has some drawbacks, though, including destruction of results that might have taken a long time to compute. (E.g. if you want to see the current diff of your changes to the notebook source vs what's in git, but you also don't want to lose your current output/results/state, what do you do?)

The alternative workflow suggested here is to work in your own copies of the notebooks, then whenever you want you can just copy your notebook over the one in the git repository, and clear the output/metadata from that copy, then inspect the source diffs - without disrupting your working/running notebook. Similarly, you can pull new changes to see someone else's changes without affecting your own notebook. Of course this workflow also isn't ideal, but at least it makes certain things possible, and it's straightforward.

(I should note there's another alternative: if a tool such as nbdime is now good enough and reliable enough - and simple enough to set up (on all platforms) - then that could be better than the above workflow for developers.)

**Comment by kcpevey** [comment]
Aha, I wasn't aware of that workflow. You're right, it makes sense to me now.   
  
I'm ok with closing this.
