### ISSUE TITLE
Clarify developer instructions

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#175]
The EarthSim website installation instructions have a section for 'developers'. Its not clear from the website what this call does:   
`conda install -c pyviz/label/dev -c conda-forge --file=dependencies-dev-overrides.txt`
  
So I executed the above call and from what I can tell, it removed the main pyviz dependecies (gv, hv, param, etc) and switched them to versions on pyviz/label/dev. Is that correct?  
  
Next question, and I know this has been discussed in painful detail, but I want to make sure I understand correctly - Are all the pyviz packages now automagically generating conda packages and putting them onto pyviz/label/dev after every PR merge?   
   
If that is correct, then I just need to run that command to update my env to all the pyviz master repos?

**Comment by ceball** [comment]
> Its not clear from the website what this call does

Thanks - I'll add some explanation to the website.

> and from what I can tell, it removed the main pyviz dependecies (gv, hv, param, etc) and switched them to versions on pyviz/label/dev

Yes, that's right.

> Next question, and I know this has been discussed in painful detail, but I want to make sure I understand correctly - Are all the pyviz packages now automagically generating conda packages and putting them onto pyviz/label/dev after every PR merge?

I'm impressed you've kept track at all :) Originally, what you describe is how I wanted it to be. However, the pyviz team preferred a different system: a conda package is only built, tested, and uploaded to pyviz/label/dev when a dev tag (e.g. v1.2.3a4) is pushed to the corresponding repo. So the packaging and testing is still automated (as originally planned), but now it requires a deliberate trigger from a developer (rather than just occurring automatically after a PR is merged to master). 

So, what you get when you run that command is the latest dev releases of pyviz packages, not necessarily the latest possible versions. As long as package authors frequently push dev tags, the end result is similar.

(Separately, of the pyviz packages in use for earthsim, only holoviews still requires manual package building and uploading. That will change soon, I hope! The rest have automated package building/testing/uploading when a dev tag is pushed.)

**Comment by ceball** [comment]
Part of #117

**Comment by jbednar** [comment]
Just so it's completely clear, having a new version on dev/ is trivial (for all but holoviews); we just have to run a single command for any package to end up on dev/. So if you ever need changes not yet on pyviz/label/dev, just ask, and we should be able to trigger a build without having to do any work.

**Comment by kcpevey** [comment]
@jbednar would you recommend to me personally that I follow the dev instructions and rely on the packages in /pyviz/label/dev channel?   
  
If that's true, every time someone mentions that something has been merged (with the exception of holoviews), I'll assume that the trigger has been pulled to also build the dev release. Because the alternative is to go and compare versions of the package to the repo everytime someone says something has been merged.

**Comment by jbednar** [comment]
If you always want to have a copy of the result of ever PR merged, you should probably be using github master for all those projects.  That's what I do, personally, and probably what Chris and Philipp do.  But for you and anyone else actually using the code to do real work, that method will eventually break things, because at some point we'll be in the middle of things.  So it's up to you; if you more often have problems with code we've fixed that you don't have yet, than you do with code we just wrote and isn't solid yet, then use master; otherwise use pyviz/label/dev.  Your choice! :-)

**Comment by kcpevey** [comment]
Ok thanks. Given that at this point, I'm on the edge of my seat waiting for merges to happen, I'll use github master.

**Comment by kcpevey** [comment]
Since this is still open, I'll add a few more comments to add to 'clarify developer instructions'...   
  
1. Developers don't often go to the user-guide Getting started page, which is where these instructions currently sit. I suggest that they be duplicated in the repo readme.   
2. Developers don't often actually read the fluffy getting started docs even if they did find themselves on the page for installation help. I think very few people would read the entire page and realize that there is an additional command at the bottom of the page for developers.
