### ISSUE TITLE
TriMesh display resolution

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#23]
It seems like I used to get much higher resolution (perhaps a vector display?) from a TriMesh visualization. Now, the mesh resolution (edges) is fairly low. It DOES dynamically adjust with zoom, but it's never at a reasonable resolution. Is there a setting to adjust this?  
  
![capture](https://user-images.githubusercontent.com/15659110/36598112-be63ec06-1870-11e8-8c80-c8e7d5318591.PNG)

**Comment by philippjfr** [comment]
By default the resolution matches the resolution of your screen, so I don't think there is anything that can be done here. Are you referring to the aliasing?

**Comment by jbednar** [comment]
@philippjfr, if you click on that screenshot above, you can see that the datashader resolution does *not* match the screen resolution (compare the blocky trimesh lines to the smooth axis labels).  So it's definitely not using the correct resolution in this case.  Usually when I see that it's because it's defaulting to `datashade()`'s relatively low default resolution rather than getting updated to the actual screen resolution, but that shouldn't be happening here, because you say it *is* updating on zooms (implying that the dynamic map behavior is working).  So something seems amiss.

You could try adding `height=1200, width=1200` to the `datashade()` or `rasterize()` or `aggregate()` call, though that *shouldn't* be needed unless something is broken with how we are fetching the plot's actual resolution.

**Comment by philippjfr** [comment]
>though that shouldn't be needed unless something is broken with how we are fetching the plot's actual resolution.

That shouldn't have any effect, since the PlotSize stream will override it. My only guess would be that it's not handling certain HiDPI screens correctly, but since things are specified in pixels I don't know why that would be the case.

**Comment by jbednar** [comment]
@kcpevey, any idea what's changed between when it was working for you and now?  Different machine, different display, different code, ...?

**Comment by kcpevey** [comment]
I think @philippjfr may be correct. If I zoom the webpage/notebook, I can find a threshold where the blocky display starts and continues as I zoom in further. If I zoom out beyond that threshold, I get the expected resolution.
  
It looks good at this notebook zoom level:
![capture2](https://user-images.githubusercontent.com/15659110/36602262-34b06932-187d-11e8-8639-a7f19fe9f380.PNG)

**Comment by kcpevey** [comment]
So basically, the display of the TriMesh (NOT the other drawing tools) is affected by the zoom level of the notebook browser.

**Comment by kcpevey** [comment]
After a quick comparison, this resolution problem is occurring with `datashade(trimesh.edgepaths)` but not with `trimesh.edgepaths`. So the problem lies within datashader and is linked somehow to the zoom level of the browser.

**Comment by jbednar** [comment]
Following on from our discussion in another issue, the problem wouldn't actually be in Datashader, which simply renders to whatever resolution it is asked.  The HoloViews datashade() operation is requesting a certain resolution, which it gets by looking up Bokeh's initial resolution, so it would presumably be some issue there.  Does the resolution update if you re-execute the cell *after* adjusting the zoom level of your browser?

**Comment by kcpevey** [comment]
@jbednar Re-executing the cell after adjusting the zoom results in the same original, poorly resolved mesh (at the original zoom extents).   
  
If you were asking me to re-execute the cell at a NEW first-draw zoom level, then I need some pointers on syntax since it appears that `datashade(trimesh.edgepaths) doesn't accept the extents I'm trying to feed it.

**Comment by kcpevey** [comment]
@jbednar Actually, I think it might be a combination of both of those. I'll screen share for clarification tomorrow.

**Comment by philippjfr** [comment]
Here's what it looks like on my Windows 7 machine.

Simple example:

![bokeh_plot](https://user-images.githubusercontent.com/1550771/41600476-eb4cadc6-73cd-11e8-922a-25e5d0e44d1d.png)

Chesepeake Bay:

![bokeh_plot 1](https://user-images.githubusercontent.com/1550771/41600490-f5e17ab4-73cd-11e8-8e37-6371282d36a0.png)

**Comment by jbednar** [comment]
We need to establish whether there is some underlying datashader issue here, as there should never be gaps in the lines like:
![image](https://user-images.githubusercontent.com/1695496/41617942-611f993e-73c7-11e8-8c46-dee2d49b44ce.png)
@philippjfr, can you extract the array from the above call and verify that there is in fact a gap there, and that it's not just being re-rendered poorly?  If there's a gap, it would be great if you could reproduce it outside of HoloViews so that we can chase down the underlying issue in Datashader (if any); the line algorithm in Datashader certainly should not be skipping any points like that.

**Comment by kcpevey** [comment]
@jbednar in reference to your last comment, during a demo I noticed this same behavior under certain circumstances. At one point it was definitely contiguous and looked great, a few minutes later after I messed around (panning, zooming, who knows...) it started looking like the above. I went back after the demo to try and recreate the situation and now I can't make it happen again :-/  . At any rate, that seems to point to a re-rendering problem?

**Comment by kcpevey** [comment]
> We need to establish whether there is some underlying datashader issue here, as there should never be gaps in the lines  
  
I have an 8M node mesh where I'm seeing this gapping behavior regardless of my zoom level.  
![trimesh_2](https://user-images.githubusercontent.com/15659110/44856928-43c41180-ac34-11e8-86b6-b010f53dc4f7.PNG)
  
![trimesh_3](https://user-images.githubusercontent.com/15659110/44856937-47579880-ac34-11e8-9357-0dbaebd6bbb8.PNG)
  
I'm using JupyterLab. In this same instance, same kernel, same browser zoom level, I ran the `Specifying_Meshes.ipynb` from earthsim/examples and I don't see the same behavior. Maybe its related to mesh size?

**Comment by jbednar** [comment]
Right. We have a set of related Datashader issues that we can address as a group in our next phase of work.

**Comment by philippjfr** [comment]
As Jim says we will be addressing a number of datashader issues as part of the next milestone but I can't explain that gapping behavior at all really.

**Comment by kcpevey** [comment]
I'm not seeing this in my current implementation. Closing.

**Comment by philippjfr** [comment]
>I'm not seeing this in my current implementation. Closing.

That's simultaneously surprising and great to hear.
