### ISSUE TITLE
param dropdown and images?

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#249]
Supposing someone wanted to get a param.ObjectSelectorList or something similar with all the colorbars in `colorcet` http://colorcet.pyviz.org, would it be possible to do that with each of them being rendered as images of the colorbars? So I guess the general question is: Can I get a parameterized dropdown list that is populated with hv.Images?

**Comment by jbednar** [comment]
Ooh, that's a fun question!  I have no idea.

**Comment by kcpevey** [comment]
@jbednar I think I've seen a demo of the colorbars rendered as an object selector, but I can't remember where. Can you point me to it?

**Comment by jbednar** [comment]
I still think that's a great idea, with a selector being able to use text, images, or text + images (for icons, colorbars, avatars, etc.).  But I don't think I've seen that for Bokeh selectors. @jsignell, have you?

**Comment by jsignell** [comment]
So the selector would display an image rather than text? I haven't seen that. The closest I've seen is the [color picker](http://panel.pyviz.org/reference/widgets/ColorPicker.html#gallery-colorpicker) which isn't really a selector in the same sense. I think we'd need to write a new dropdown menu to accommodate displaying images in it.

**Comment by philippjfr** [comment]
Yeah, that would definitely require a new bokeh model.

**Comment by kcpevey** [comment]
The color picker is the thing I was thinking about. I don't think building a new bokeh model is within scope at this point.

**Comment by jbednar** [comment]
That's a shame; seems like a fun task to work on. :-)
