### ISSUE TITLE
Update EarthSim examples and docs to use string aggregator fns

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#62]
From this example notebook: https://github.com/pyviz/EarthSim/blob/master/examples/user_guide/Visualizing_Meshes.ipynb  
  
I have the following snippets:  
```
import datashader as ds
from holoviews.operation.datashader import datashade, rasterize
  
datashade(trimesh, aggregator=ds.mean('z'))
```
  
I'm trying to understand the difference between `datashade` and `datashader`. Why are they in two totally different repositories, but required for the generation of a single datashaded drawing?

**Comment by jlstevens** [comment]
I agree that needing to import the aggregators from ``datashader`` in order to use ``datashade`` is awkward. We have had some discussion trying to address this issue in the past, but I can't remember what we decided. @jbednar ?

**Comment by jlstevens** [comment]
Why not make ``ds`` available from ``holoviews.operation.datashader``? Then it could be:

```
from holoviews.operation.datashader import datashade, rasterize, ds
datashade(trimesh, aggregator=ds.mean('z'))
```

**Comment by jbednar** [comment]
`ds` is actually already available there, so your suggestion should work already.  I hadn't thought of that approach.  @philippjfr, any opinions?

**Comment by philippjfr** [comment]
Not a huge fan of importing other libraries from a module of another library so I probably wouldn't use it personally, but it's certainly a valid approach. Separately, ``datashade`` also gained the ability to interpret strings and appropriately infer the dimension, e.g.

```python
from holoviews.operation.datashader import datashade, rasterize
  
datashade(trimesh, aggregator='mean')
```

should be equivalent to the more explicit approach above and will work fine as long as you want to refer to the first value dimension (of which there should only be one in this case).

**Comment by jbednar** [comment]
Good point.  Here it's mainly a question of documentation -- how do we recommend, from the point of view of a HoloViews user, that people typically work?  That's the style we should put into our docs, and only separately mention that there is another way if some people need that.

Here, if we want to encourage people to use the string format so that they are only using entities directly available from HoloViews, then we need to change our examples to do that consistently, and then not `import datashader`.  In that case we'd presumably mention as an aside that people can also import directly from datashader if they need more control over the arguments to the aggregators, but then point only to the Datashader docs to show that, not include it in the HoloViews docs.  Seems reasonable to me.

**Comment by jlstevens** [comment]
> ... and will work fine as long as you want to refer to the first value dimension

That is the issue using strings imho. Otherwise, I agree that strings would be better here.
